-- Migration: 022_support_documents_seed.sql
-- Description: Seeding highly accessible, user-centric, and legally robust Terms of Service and Privacy Policy in English.
-- Compliance: Aligning with GDPR, CCPA, HIPAA, COPPA, Indonesian UU PDP No. 27/2022, and E-E-A-T guidelines.

-- Ensure the support_documents table receives the data cleanly and idempotently
INSERT INTO public.support_documents (slug, title, content_markdown, updated_at)
VALUES 
(
  'terms',
  'Terms of Service',
  $$# Terms of Service for LifeBloom Hub
*Last Updated: May 27, 2026*

Welcome to **LifeBloom Hub**, a peaceful digital harbor and high-utility calculation center designed with empathy to help individuals, caregivers, and families navigate health, financial wellness, domestic living, pet care, and multi-generational travel safely and independently.

These Terms of Service ("Terms") constitute a legally binding agreement between you and LifeBloom Hub. By accessing or using our platform, including our interactive calculators, community forums, real-time streams, and localized reading materials, you agree to be bound by these Terms. If you do not agree to these Terms, please do not access or use the platform.

---

## 1. Our Mission, E-E-A-T, and Uncluttered Experience
LifeBloom Hub is built on the pillars of transparency, senior accessibility, and scientific/clinical integrity.
* **Clinical & Financial Trust (E-E-A-T):** We collaborate with Verified Experts (clinicians, certified financial planners, and researchers) to audit and approve our educational content. Our articles feature verified digital signatures linked to academic and professional registries like ORCID and Wikidata.
* **No-Banner Policy:** To protect our users—particularly senior citizens—from cognitive overload, malicious redirects, and invasive behavioral profiling, we strictly reject traditional programmatic banner advertisements. Our sustainable monetization is integrated as contextual, high-integrity "Stewardships" within our interactive tools.

---

## 2. Professional Advice Disclaimers (Crucial Safety Limits)
Your safety is our absolute priority. Please read these limits carefully:

### 2.1. Medical and Clinical Information Disclaimer
* **No Medical Advice:** LifeBloom Hub provides tools, checklists, and search systems (such as the *Canine Symptom Checker* and the *Senior Drug Checker*) that query public medical databases, including the **U.S. Food and Drug Administration (OpenFDA)** and the **U.S. National Library of Medicine (DailyMed)**.
* **Educational Purposes Only:** All output, drug interaction alerts, symptom matches, and safety flags generated by our tools are purely for informational and educational purposes. **They do not constitute professional medical advice, veterinary advice, diagnosis, or treatment plans.**
* **Consult a Professional:** Always seek the advice of your physician, pharmacist, or veterinarian regarding any medical or veterinary condition, prescription medications, or wellness regimens. Never disregard professional advice or delay seeking it because of something you have read on this platform.

### 2.2. Financial and Investment Disclaimer
* **No Financial Advice:** LifeBloom Hub provides compounding yield planners, retirement calculators, and macro-economic estimators (such as the *Retirement Planner* and *Yield Radar*) that query datasets from **FRED (Federal Reserve Economic Data)**.
* **Educational Simulations Only:** All calculations, compound yield models, and safety scores are hypothetical, mathematical simulations intended for financial literacy education. **They do not constitute professional financial, tax, or investment advice, nor do they establish an advisor-client relationship.**
* **Consult a Professional:** Always consult a Certified Financial Planner (CFP) or licensed tax professional before making major investment, retirement, or tax-planning decisions.

---

## 3. User Accounts & Supabase Authentication Security
You can access our core calculation utilities anonymously. However, to unlock premium features—such as saving calculation history, planning multi-generational itineraries, or participating in discussions—you may create an account via our secure **Supabase Authentication** gateway.
* **Account Security:** You are entirely responsible for maintaining the confidentiality of your credentials. You agree to notify us immediately of any unauthorized use of your account.
* **No Credential Harvesting:** LifeBloom Hub will never ask for your password via email, SMS, WhatsApp, or any other external channel. Treat any such request as a malicious phishing attempt and report it immediately.
* **Termination:** We reserve the right to suspend or terminate accounts that violate our community standards or compromise platform security.

---

## 4. Community Conduct & Threaded Discussion Ethics
To maintain a safe harbor, all members participating in our threaded comment sections (*Accessible Comments*) or our wall of encouragement (*Real-time Guestbook*) must adhere to our strict Code of Conduct:
* **Generational Empathy:** Treat all members with respect, patience, and kindness. Many of our users are seniors or caregivers facing challenging situations; toxic, aggressive, or dismissive language will not be tolerated.
* **No Spam or Self-Promotion:** Do not post unauthorized advertisements, affiliate links, repetitive spam, or malicious scripts. All comments are subjected to automated filtering and a strict manual moderation queue (`is_approved = false` by default).
* **No Malicious Inputs:** Any attempts to inject malicious HTML, Cross-Site Scripting (XSS) payloads, or SQL injections into our text fields will result in an immediate permanent ban and, if necessary, reporting to cyber-security authorities.

---

## 5. Intellectual Property & Fair Use Licensing
* **Proprietary Rights:** All proprietary code, custom mathematical algorithms, interactive calculator architectures, the unique "Organic Minimalist" design system (including Pebble Card layouts), and original articles on LifeBloom Hub are protected under global copyright and intellectual property laws.
* **Personal License:** We grant you a limited, non-transferable, revocable license to print, download, or share outputs from our calculators (such as your personal *Mobility Safety Checklist*) for personal, family, or professional consultation use (e.g., sharing the PDF output with your family doctor).
* **No Scrapes:** Automated scraping of our translated database, structured article repositories, or database endpoints for the purpose of training commercial AI models or republishing on ad-laden websites is strictly prohibited without explicit written consent.

---

## 6. High-Integrity Affiliate Partnership Disclosure
LifeBloom Hub selectively integrates premium, contextually relevant affiliate partnerships (including Travelpayouts, Partnerize, and Impact.com). When you interact with a partner's booking tool or clear a recommended travel itinerary from our platform, we may receive a small financial commission from the partner. This commission comes at absolutely zero additional cost to you, our user, and helps us keep our high-utility calculation tools free, secure, and independent from tracking-based banner ads.

---

## 7. Limitation of Liability & Indemnification
* **As-Is Provision:** LifeBloom Hub and its open-source API adapters (OpenFDA, FRED, USDA) are provided on an "as-is" and "as-available" basis. We do not guarantee that the services will be completely uninterrupted, secure, or free from factual errors.
* **Limitation:** To the maximum extent permitted by applicable law, LifeBloom Hub, its directors, employees, and verified expert contributors shall not be liable for any direct, indirect, incidental, or consequential damages resulting from your reliance on our tools, calculations, or articles.
* **Indemnification:** You agree to indemnify and hold harmless LifeBloom Hub and its associates from any claims, losses, or legal liabilities arising from your violation of these Terms or your misuse of the platform.

---

## 8. Governing Law & Dispute Resolution
These Terms are governed by and construed in accordance with the laws of Delaware, United States (or the primary corporate jurisdiction of LifeBloom Hub), without regard to its conflict of law principles. Any legal action or proceeding arising out of or related to these Terms shall be resolved through binding, confidential arbitration in accordance with global commercial arbitration standards.

---

## 9. Revisions & Platform Contact
We may update these Terms periodically to reflect legislative changes, database enhancements, or security upgrades. We will notify you of any structural updates by placing an intuitive, high-contrast banner on your dashboard.

If you have any questions, concerns, or feedback regarding these Terms, please contact our administrative team at:
* **Email:** `support@lifebloomhub.com`
* **Subject:** *TOS Inquiry*
$$,
  now()
),
(
  'privacy',
  'Privacy Policy',
  $$# Privacy Policy for LifeBloom Hub
*Last Updated: May 27, 2026*

At **LifeBloom Hub**, we believe that your personal data is a sacred trust, not a tradeable commodity. We treat your privacy like an honored guest in our home—protected with absolute respect, total transparency, and state-of-the-art technological safeguards.

This Privacy Policy is designed to comply with global privacy standards, including the **General Data Protection Regulation (GDPR)**, the **California Consumer Privacy Act (CCPA)**, the **Health Insurance Portability and Accountability Act (HIPAA)** guidelines for medical data handling, and the **Indonesian Personal Data Protection Act (UU PDP No. 27/2022)**.

---

## 1. The Core Philosophy of Data Minimization
We collect only the absolute minimum amount of information necessary to deliver high-utility calculations and localized health summaries to you.
* **We do not track your behavioral patterns across the web.**
* **We do not sell, rent, or trade your data with ad brokers.**
* **We process calculations locally on your device whenever possible.**

---

## 2. Information We Collect & How We Use It

### 2.1. Account and Profile Data (Supabase Auth)
When you register for a member account, we store your email address and profile details securely in our encrypted **Supabase** database. This data is used solely to authenticate your identity, save your personal calculation history, and remember your accessibility preferences (such as large font sizes or high-contrast styles).

### 2.2. Interactive Calculator Inputs (Local Processing & Ephemeral State)
When you input parameters into the *Senior Drug Checker*, *Retirement Planner*, or *Pet Planner*, we process these inputs temporarily. 
* **Anonymous Use:** If you use our tools without logging in, your inputs remain entirely in your browser's local memory and are never saved to our database.
* **Saved History:** If you are logged in and explicitly click "Save to My Harbor," your calculation parameters are sent via encrypted transit to Supabase and secured behind strict Postgres **Row-Level Security (RLS)**, ensuring only you can access them.

### 2.3. Contextual Sponsor Telemetry (Google BigQuery Data Warehouse)
To fund our platform without resorting to tracking banners, select contextual sponsors finance our calculators. When you run a calculation (e.g., estimating travel budgets), we stream anonymous telemetry logs (such as the date, pilar name, and general country location) to **Google BigQuery** via secure Server-to-Server GCP Service Account tokens. **We never send your name, email, medical inputs, or financial quantities to Google BigQuery or to any sponsor.**

### 2.4. Communications & Support Ingest
If you submit an inquiry through our contact form, we collect your name, email, and message. This data is handled in strict confidence and is used solely by our administrators to assist you with your request.

---

## 3. Data Protection and SRE Security Protocols
We implement rigorous, production-grade security architecture to shield your data from unauthorized access, modification, or leakage:
* **Strict Row-Level Security (RLS):** All data rows in Supabase are isolated at the database level. RLS policies actively verify that an authenticated session matches the specific owner's ID (`auth.uid() = user_id`) before granting read/write privileges.
* **Upstash Redis Enkripsi:** To deliver instanced localized reading layouts, hot temporary assets are cached in **Upstash Redis**. All cache keys are generated deterministically using SHA-256 cryptographic hashes of the raw text, detaching your identity completely from the cached text.
* **SSL/TLS Encryption:** All data in transit is encrypted using advanced TLS 1.3 protocols.
* **Database Isolation:** Our database runs behind isolated network ports on Supabase, guarded against direct exterior entry.

---

## 4. Cookies & Push Notifications

### 4.1. Functional Cookies
We use minimal, high-contrast, first-party functional cookies solely to remember:
* Your language preference (`[locale]`) so you don't have to select it on every visit.
* Your onboarding status so we don't display the introductory overlay repeatedly.
We do not use third-party tracking or retargeting cookies.

### 4.2. Push Notifications (OneSignal)
If you opt-in to receive critical wellness alerts, drug recall notifications, or platform updates, we deliver these via **OneSignal**. 
* OneSignal may collect anonymous device parameters to deliver push payloads successfully.
* You can easily revoke this permission at any time directly through your web browser's notification settings.

---

## 5. Global Privacy Rights (GDPR, CCPA, & Indonesian UU PDP)
No matter where you live in the world, LifeBloom Hub grants you absolute control over your personal data. You are entitled to the following rights:

* **The Right to Access:** You can request a clear report of all personal data we hold about your profile.
* **The Right to Rectification:** You can update or correct any inaccurate personal details in your account dashboard.
* **The Right to Erasure (The Right to be Forgotten):** You can request the permanent deletion of your account, saved calculations, and contact history.
* **The Right to Data Portability:** You can request a copy of your saved data in a clean, structured JSON format.

To exercise any of these rights, simply go to your dashboard settings or email our Data Protection Officer at `privacy@lifebloomhub.com`. We will process and confirm your request free of charge within 48 hours.

---

## 6. Children's Privacy (COPPA Compliance)
LifeBloom Hub is designed for families, caregivers, and adults managing household wellness. We do not knowingly collect or maintain personal data from children under the age of 13. If we discover that a child under 13 has created an authenticated account, we will immediately delete their profile and associated records permanently.

---

## 7. Contact Our Data Protection Officer (DPO)
If you have any questions, security concerns, or privacy policy inquiries, our dedicated Data Protection Officer is ready to assist you in a warm and professional manner.

* **Email:** `privacy@lifebloomhub.com`
* **Subject:** *Data Privacy Inquiry*
* **Response Guarantee:** Within 48 business hours.
$$,
  now()
)
ON CONFLICT (slug) 
DO UPDATE SET 
  title = EXCLUDED.title,
  content_markdown = EXCLUDED.content_markdown,
  updated_at = EXCLUDED.updated_at;